server:
    port: 8081
    servlet:
        context-path: /Shopme
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopme
        password: shopme
        username: shopme
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 94253779234-hpi81ep6ne1eiqahodqf7qn3m2rcv1qn.apps.googleusercontent.com
                        client-secret: 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
                        scope: email, profile
