server:
  servlet:
    context-path: /ShopmeAdmin
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopme
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
